/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.pavo.ui;

import com.itson.pavo.entidades.Persona;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author mmenu
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Crear nuevo fomulario de usuario
     */
    public Formulario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbSexo = new javax.swing.JComboBox<>();
        jEstado = new javax.swing.JComboBox<>();
        txtResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Generador de CURP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 22, -1, -1));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Por favor ingrese todos los datos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 59, -1, -1));

        btnGenerar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(67, 111, 225));
        btnGenerar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGenerar.setText("Generar");
        btnGenerar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 111, 225)));
        btnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 70, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 111, 225));
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 111, 225)));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 190, 30));

        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 111, 225)));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 111, 225));
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(67, 111, 225));
        jLabel7.setText("Año");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtAño.setForeground(new java.awt.Color(102, 102, 102));
        txtAño.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 111, 225)));
        jPanel1.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(67, 111, 225));
        jLabel8.setText("Mes");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        txtMes.setForeground(new java.awt.Color(102, 102, 102));
        txtMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 111, 225)));
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 50, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(67, 111, 225));
        jLabel9.setText("Día");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        txtDia.setForeground(new java.awt.Color(102, 102, 102));
        txtDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 111, 225)));
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 40, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(67, 111, 225));
        jLabel10.setText("Estado");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jbSexo.setForeground(new java.awt.Color(67, 111, 225));
        jbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "hombre", "mujer" }));
        jPanel1.add(jbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jEstado.setForeground(new java.awt.Color(67, 111, 225));
        jEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila de Zaragoza", "Colima", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán de Ocampo", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz de Ignacio de la Llave", "Yucatán", "Zacatecas", "Nacido en el Extranjero" }));
        jPanel1.add(jEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtResultado.setForeground(new java.awt.Color(67, 111, 225));
        txtResultado.setText("Su CURP es :");
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 330, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseClicked
        // TODO add your handling code here:
        try {
            Persona persona = new Persona();

            persona.setNombre(txtNombre.getText());
            persona.setApellido(txtApellido.getText());
            persona.setDia(txtDia.getText());
            persona.setAño(txtAño.getText());
            persona.setEstado(jEstado.getSelectedItem().toString());
            persona.setMes(txtMes.getText());
            persona.setGenero(jbSexo.getSelectedItem().toString());
            if(
                    !persona.getNombre().equals("") &&
                    !persona.getApellido().equals("") &&
                    !persona.getDia().equals("") &&
                    !persona.getApellido().equals("") &&
                    !persona.getEstado().equals("") &&
                    !persona.getMes().equals("") &&
                    !persona.getGenero().equals("")
            ){
                String curp ="";
            

    //        Primera letra del primer apillido 
            curp = String.valueOf(persona.getApellido().charAt(0));
    //        primera vocal interna del primer apellido
            char[] apellidoArr = persona.getApellido().toCharArray();
            System.out.println(apellidoArr[1]);
            for(int i = 0; i < apellidoArr.length; i++ ){
                if("aeiou".indexOf(apellidoArr[i]) != -1 && "aeiou".indexOf(apellidoArr[i]) != 0){
                    curp += apellidoArr[i];
                    break;
                }
            }
    //        Primera letra del segundo apellido. En caso de no tener segundo apellido, se colocará X.
            if(persona.getApellido().split(" ").length > 1){
                curp += persona.getApellido().split(" ")[1].charAt(0);
            }else{
                curp += "X";
            }

    //        Primera letra del nombre de pila. En nombres compuestos que comiencen con José o María, 
    //        se tomará en cuenta la primera letra segundo nombre
            if(persona.getNombre().split(" ").length > 1){
                curp += persona.getNombre().split(" ")[1].charAt(0);
            }else{
                curp += persona.getNombre().charAt(0);
            }

            curp += persona.getAño().substring(persona.getAño().length() - 2, persona.getAño().length())+""+persona.getMes()+""+persona.getDia();

            curp += persona.getGenero().charAt(0);
    //        Dos letras correspondientes a la entidad de nacimiento. Consultar las claves aquí.
              listaEstados(persona.getEstado(), persona);
              curp += persona.getEstadoCodigo();

    //         Primera constante interna (no inicial) del primer apellido
            for(int i = 1; i < apellidoArr.length; i++ ){
                if("aeiou".indexOf(apellidoArr[i]) == -1){
                    curp += apellidoArr[i];
                    break;
                }
            }

    //        Primera consonante interna (no inicial) del segundo apellido. En caso de no tener segundo apellido, se colocará X.
            if(persona.getApellido().split(" ").length == 1){
                curp += "X";
            }else{
             String segundoApellido = persona.getApellido().split(" ")[1];
                char[] segundoApellidoArr = segundoApellido.toCharArray();
                for(int i = 1; i < segundoApellidoArr.length; i++ ){
                    if("aeiou".indexOf(segundoApellidoArr[i]) == -1 && i > 0){
                        curp += segundoApellidoArr[i];
                        break;
                    }
                }   
            }
//            Primera consonante interna (no inicial) del nombre
            char[] nombre = persona.getNombre().toCharArray();

            for(int i = 1; i < nombre.length; i++ ){
                    if("aeiou".indexOf(nombre[i]) == -1 && i > 0){
                        curp += nombre[i];
                        break;
                    }
                }

            if(Integer.parseInt(persona.getAño()) <= 1999){
                curp += "0";
            }else{
                curp += "A";
            }

            curp = curp.toUpperCase();
           txtResultado.setText(txtResultado.getText()+curp);
            }else{
                JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
            }
        } catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarMouseClicked
    
    /*
    * @params p, estado
    */
    private void listaEstados(String estado, Persona p){
        try {
            Map<String, String> map = new HashMap<>();
            map.put("AS", "Aguascalientes");		map.put("CS", "Chiapas");
            map.put("BC", "Baja California");		map.put("CH", "Chihuahua");
            map.put("BS", "Baja California Sur");	map.put("DF", "Distrito Federal");
            map.put("CC", "Campeche");                  map.put("DG", "Durango");
            map.put("CL", "Coahuila de Zaragoza");	map.put("GT", "Guanajuato");
            map.put("CM", "Colima");                    map.put("GR", "Guerrero");
            map.put("HG", "Hidalgo");                   map.put("JC", "Jalisco");
            map.put("MC", "México");                    map.put("MN", "Michoacán de Ocampo");
            map.put("MS", "Morelos");                   map.put("NT", "Nayarit");
            map.put("NL", "Nuevo León");                map.put("OC", "Oaxaca");
            map.put("PL", "Puebla");                    map.put("QT", "Querétaro");
            map.put("QR", "Quintana Roo");              map.put("SP", "San Luis Potosí");
            map.put("SL", "Sinaloa");                   map.put("SR", "Sonora");
            map.put("TC", "Tabasco");                   map.put("TS", "Tamaulipas");
            map.put("TL", "Tlaxcala");                  map.put("VZ", "Veracruz de Ignacio de la Llave");
            map.put("YN", "Yucatán");                   map.put("ZS", "Zacatecas");
            map.put("NE", "Nacido en el Extranjero");
            map.forEach((k, v)->{
                if(v.equals(estado)){
                    p.setEstadoCodigo(k);
                }
            });
        } catch (Exception e) {
            System.out.println("error: "+e.getMessage());
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGenerar;
    private javax.swing.JComboBox<String> jEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jbSexo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
